### ISSUE TITLE
Qual deve ser o escopo do grupo Desenvolvimento Web?

### ISSUE THREAD

**Issue by netojoaobatista** [GrupoDesenvolvimentoWeb/GrupoDesenvolvimentoWeb.github.io#4]
# Definição

O escopo é a base de qualquer comunidade. É a partir do escopo que as regras são elaboradas. Para elaborar um bom conjunto de regras, que atenda aos objetivos da comunidade como um todo, precisamos responder a seguinte pergunta: **Qual deve ser o escopo do grupo Desenvolvimento Web?**

1. Tirar dúvidas sobre desenvolvimento relacionado com web.
2. Obter dicas sobre desenvolvimento relacionado com web.
3. Obter dicas de ferramentas e tecnologias relacionadas com desenvolvimento web.
4. Contar piadinhas, descontrair e confraternizar virtualmente com outros desenvolvedores web.
5. Compartilhar conteúdo pessoal para autopromoção.
6. Compartilhar links e sites de empresa como publicidade.
7. Compartilhar e/ou encontrar ofertas para freelancers ou oportunidades de trabalho.
8. Compartilhar e/ou encontrar dicas de cursos, livros, eventos, etc.

## Como votar

Por favor, comentem a issue apenas com números, um número por linha, com os itens que desejam definir como escopo do grupo. Por exemplo:

```
1
2
3
8
```

### Totalização dos votos

|Item|Total de votos|Porcentagem|
|-----|-------------------|----------------|
|3|30 votos|100%|
|1|29 votos| 96%|
|2|29 votos| 96%|
|8|25 votos|  83%|
|7|18 votos|  60%|
|6|2 votos|   6%|
|4|1 votos|   3%|
|5|1 votos|   3%|

### Itens aprovados

* Tirar dúvidas sobre desenvolvimento relacionado com web.
* Obter dicas sobre desenvolvimento relacionado com web.
* Obter dicas de ferramentas e tecnologias relacionadas com desenvolvimento web.
* Compartilhar e/ou encontrar ofertas para freelancers ou oportunidades de trabalho.
* Compartilhar e/ou encontrar dicas de cursos, livros, eventos, etc.

Os itens 6, 4 e 5 não alcançaram 50% dos votos e, por isso, foram considerados como não válidos para o escopo do grupo Desenvolvimento Web

**Comment by hebertporto** [comment]
1
2
3
7
8

**Comment by estudioprogramacaocriativa** [comment]
1
2
3
7
8

**Comment by edsonlimadev** [comment]
1
2
3
8

**Comment by sayroz** [comment]
1
3
7
8

**Comment by Bolinha1** [comment]
1
2
3
7
8

**Comment by eduiagami** [comment]
1
2
3

**Comment by vagnerld** [comment]
1
2
3
7
8

**Comment by ivanrosolen** [comment]
1
2
3
8

**Comment by sio-iago** [comment]
1
2
3
7

**Comment by allanbobs** [comment]
1
2
3
8
7

**Comment by dvl** [comment]
1
2
3

**Comment by GuilhermeOmetto** [comment]
1
2
3
8

**Comment by WarleyFranco** [comment]
1
2
3
7
8

**Comment by ktquez** [comment]
1
2
3
7
8

**Comment by marcioabraz** [comment]
1
2
3
7
8

**Comment by brunoracosta** [comment]
1
2
3
8

**Comment by luizlazaro** [comment]
1
2
3
7
8

**Comment by hevertoncastro** [comment]
1
2
3
7
8

**Comment by MouraRenan** [comment]
1
2
3
8

**Comment by naison-souza-praxis** [comment]
1
2
3

**Comment by leandroprog** [comment]
1
2
3
7
8

**Comment by augustolima** [comment]
1
2
3
8

**Comment by vicenterusso** [comment]
2
3
5
8

**Comment by LuizPedrosa** [comment]
1
2
3
7
8

**Comment by jfreitasdutra** [comment]
1
2
3
4
6
7
8

**Comment by pedromazala** [comment]
1
2
3
6
7
8

**Comment by robertopc** [comment]
1
2
3
8

**Comment by fndomariano** [comment]
1
2
3
8

**Comment by IgorSamer** [comment]
1
2
3
7
8

**Comment by luizadantas** [comment]
1
2
3
7
8
