### ISSUE TITLE
Regras sobre postagem de dúvidas

### ISSUE THREAD

**Issue by netojoaobatista** [GrupoDesenvolvimentoWeb/GrupoDesenvolvimentoWeb.github.io#6]
# Regras sobre postagem de dúvidas.

Existem várias categorias de dúvidas: técnicas, erros, boas práticas de desenvolvimento, utilização de ferramentas, etc.

**Antes de postar qualquer dúvida, utilize a pesquisa interna do grupo**. O Desenvolvimento Web é composto por mais de 22K membros e, muito provavelmente, alguém já passou pela mesma dificuldade que você está passando agora. Se após utilizar a pesquisa interna não encontrar nenhum post do grupo abordar sua dúvida, siga as regras abaixo para criar seu post:

## Para todos os tipos de dúvidas

1. Todos os membros devem, necessariamente, respeitar uns aos outros.
    1. Se você não sabe como resolver o problema, prefira não comentar para não atrapalhar o autor da dúvida;
    2. se você acha que o Google é a resposta, poste a busca com as respectivas palavras chave que levam à solução;
    3. se você faltar com o respeito no grupo, seu post/comentário será excluído;
    4. se você reiteradamente faltar com o respeito com outros membros, você eventualmente será punido.
2. A dúvida deve ser descrita de forma clara, direta e objetiva.
    1. Procure utilizar hashtags para marcar a tecnologia: `#php`, `#javascript`, `#css`, etc;
    2. utilize um título curto que descreva a dúvida;
    3. descreva mais detalhadamente a dúvida logo após o título;
    4. informe a tecnologia que está trabalhando, sistema operacional, mensagem de erro e/ou qualquer coisa relevante que possa ajudar na resolução do problema.
3. Não pergunte se alguém conhece ou utiliza X ou Y, ou se trabalha com Z.
    1. Poste a dúvida como descrito no item 2 e, se alguém souber responder, certamente responderá.
4. Não poste uma imagem com o erro, exceto se se tratar de um erro de renderização de layout e/ou equivalentes.
    1. Se a dúvida é sobre uma mensagem de erro de software, poste o texto da mensagem de erro e siga as recomendações do item 2 para facilitar a identificação do erro e diagnóstico.
5. Jamais poste códigos diretamente no grupo.
    1. Utilize um serviço externo para publicar o código, como github ou pastebin, poste apenas o link e siga as recomendações do item 2 para facilitar a identificação do erro e diagnóstico.
6. Jamais pergunte se tem alguém online e jamais peça ajuda por inbox.
    1. O grupo existe para que seus membros possam se ajudar; se você tira a discussão de dentro do grupo, outros membros não poderão se beneficiar da resposta para sua dúvida.

## Exemplo de post de dúvida perfeito

> Erro de consulta no banco de dados #mysql com #php
> 
> Estou tentando fazer uma consulta numa base MySQL, mas estou recebendo a mensagem Error: 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near...
> 
> Alguém sabe o que pode ser?

## Como votar

Poste o número do item seguido de um ponto e **sim** ou **não** conforme sua preferência. Se o item tiver subitens, basta indentar o subitem e seguir o padrão anterior. Por exemplo:

```
1. Sim
    1. Sim
    2. Sim
    3. Sim
    4. Sim
2. Sim
    1. Sim
    2. Sim
    3. Sim
    4. Sim
3. Sim
    1. Sim
4. Sim
    1. Sim
5. Sim
    1. Sim
6. Sim
    1. Sim
```

## Resultado da votação

Todos os membros que participaram votaram em sim para todos.

**Comment by edsonlimadev** [comment]
1. Sim
    1. Sim
    2. Sim
    3. Sim
    4. Sim
2. Sim
    1. Sim
    2. Sim
    3. Sim
    4. Sim
3. Sim
    1. Sim
4. Sim
    1. Sim
5. Sim
    1. Sim
6. Sim
    1. Sim

**Comment by paulomartinhago** [comment]
Acho que pode entrar um novo item aí nesta lista.

Muitas pessoas postam no grupo com a seguinte pergunta: Alguém entende de HTML aqui que pode me ajudar?

Esse grupo é voltado a MUITOS desenvolvedores HTML. Esta pergunta é quase um desafio pra quem vai digitar algo nos comentários.

Respondendo a lista:

1. Sim
    1. Sim
    2. Sim
    3. Sim
    4. Sim
2. Sim
    1. Sim
    2. Sim
    3. Sim
    4. Sim
3. Sim
    1. Sim
4. Sim
    1. Sim
5. Sim
    1. Sim
6. Sim
    1. Sim

**Comment by netojoaobatista** [comment]
@paulomartinhago,

> Alguém entende de HTML aqui que pode me ajudar?

Item 3 da proposta:

* [x] **Não pergunte se alguém utiliza ferramenta X ou Y, ou se trabalha com a ferramenta Z.**
    * [x] Poste a dúvida como descrito no item 2 e, se alguém souber responder, certamente responderá.

;)

**Comment by paulomartinhago** [comment]
@netojoaobatista ;)

**Comment by bene8** [comment]
sim pra tudo, só acho que ajudaria fazer um post fixo sobre hospedagem, mais de 25% das duvidas são sobre isto

**Comment by yuricamara** [comment]
@bene8 Isto já foi feito uma vez. Não funcionou. Infelizmente.  Estamos pensando numa maneira de lidar com isso.

**Comment by netojoaobatista** [comment]
Chegaremos lá, @bene8!

Ainda teremos as definições das regras sobre pedidos de dicas e indicações, que começará a abordar esse tema, e teremos as regras gerais, que trabalharão com off-topic, definições sobre comportamento geral no grupo, inclusive dos admins, etc.

Vamos tentar cercar a questão dos posts duplicados de uma forma que permita certas postagens, mas que impeça a redundância e repetição.

:smile:

**Comment by raingrave** [comment]
Bem elaborada as regras!

1. Sim
        i. Sim
        ii. Sim
        iii. Sim
        iiii. Sim

        2. Sim
        i. Sim
        ii. Sim
        iii. Sim
        iiii. Sim

3. Sim
        i. Sim

4. Sim
        i. Sim

5. Sim
        i. Sim

6. Sim
        i. Sim

**Comment by andersoncustodio** [comment]
1. Sim
    1. Sim
    2. Sim
    3. Sim
    4. Sim
2. Sim
    1. Sim
    2. Sim
    3. Sim
    4. Sim
3. Sim
    1. Sim
4. Sim
    1. Sim
5. Sim
    1. Sim
6. Sim
    1. Sim

**Comment by michelsouza** [comment]
1. Sim
   1. Sim
   2. Sim
   3. Sim
   4. Sim
2. Sim
   1. Sim
   2. Sim
   3. Sim
   4. Sim
3. Sim
   1. Sim
4. Sim
   1. Sim
5. Sim
   1. Sim
6. Sim
   1. Sim

**Comment by brunoracosta** [comment]
1. Sim
    1. Sim
    2. Sim
    3. Sim
    4. Sim
2. Sim
    1. Sim
    2. Sim
    3. Sim
    4. Sim
3. Sim
    1. Sim
4. Sim
    1. Sim
5. Sim
    1. Sim
6. Sim
    1. Sim

**Comment by thusk** [comment]
de acordo! Obrigado pela 5) ! 

1. Sim
    1. Sim
    2. Sim
    3. Sim
    4. Sim
2. Sim
    1. Sim
    2. Sim
    3. Sim
    4. Sim
3. Sim
    1. Sim
4. Sim
    1. Sim
5. Sim
    1. Sim
6. Sim
    1. Sim

**Comment by upcesar** [comment]
<ol>
<li>Sim
<ol>
<li>Sim</li>
<li>Sim</li>
<li>Sim</li>
<li>Sim</li>
</ol>
</li>
<li>
Sim
<ol>
<li>Sim</li>
<li>Sim</li>
<li>Sim</li>
<li>Sim</li>
</ol>
</li>
<li>
Sim
<ol>
<li>Sim</li>
</ol>
</li>
<li>Sim
<ol>
<li>Sim</li>
</ol>
</li>
<li>Sim
<ol>
<li>Sim</li>
</ol></li>
<li>Sim
<ol>
<li>Sim</li>
</ol></li>
</ol>

**Comment by rochamarcelo** [comment]
1. Sim
    1. Sim
    2. Sim
    3. Sim
    4. Sim
2. Sim
    1. Sim
    2. Sim
    3. Sim
    4. Sim
3. Não

4. Sim
    1. Sim
5. Sim
    1. Sim
6. Sim
    1. Sim

**Comment by henriquemoody** [comment]
1. Sim
    1. Sim
    2. Sim
    3. Sim
    4. Sim
2. Sim
    1. Sim
    2. Sim
    3. Sim
    4. Sim
3. Sim
    1. Sim
4. Sim
    1. Sim
5. Sim
    1. Sim
6. Sim
    1. Sim

Acredito que a parte de **Antes de postar qualquer dúvida, utilize a pesquisa interna do grupo** deveria estar inserida em um dos tópicos, é apenas um detalhe mas acredito que seja melhor.

**Comment by netojoaobatista** [comment]
Bem notado, @henriquemoody!

Colocaremos na seção de regras gerais, pois envolve todos os tipos de posts - não apenas os de dúvidas.

:smile:

**Comment by cardoso243** [comment]
1. Sim
    1. Sim
    2. Sim
    3. Sim
    4. Sim
2. Sim
    1. Sim
    2. Sim
    3. Sim
    4. Sim
3. Não
    1. Não
4. Sim
    1. Sim
5. Sim
    1. Sim
6. Sim
    1. Sim

**Comment by cardoso243** [comment]
Se criasse uma página para o item 3 seria interessante..

**Comment by upcesar** [comment]
@netojoaobatista seria interessante definir a linguagem dos artigos a compartilhar, sendo que por ser um grupo onde a grande maioria são de fala portuguesa e também tem muitas mais informações para nossa área em inglês que em português e mesmo em espanhol (stackoverflow, getbootstrap são alguns exemplos) e também acho que quem trabalha em computação possui um nível de leitura de inglês aceitável. Será aceito colocar post em inglês ou quem compartilhar vai ter o trabalho de traduzir, caso contrário não será publicado?

**Comment by netojoaobatista** [comment]
@upcesar, pessoalmente, postagens de artigos em inglês não me incomodam, desde que a discussão dentro do grupo seja em português. Muitas vezes o conteúdo o artigo, mesmo em inglês, trazem boas discussões em português. Enfim, pessoalmente, não vejo problemas nisso. Podemos monitorar, claro, e se começarmos a ver problemas nisso, pensamos numa solução.

:smile:

**Comment by allanbobs** [comment]
1. Sim
    1. Sim
    2. Sim
    3. Sim
    4. Sim
2. Sim
    1. Sim
    2. Sim
    3. Sim
    4. Sim
3. Sim
    1. Sim
4. Sim
    1. Sim
5. Sim
    1. Sim
6. Sim
    1. Sim

**Comment by lpgpa** [comment]
1. Sim
    1. Sim
    2. Sim
    3. Sim
    4. Sim
2. Sim
    1. Sim
    2. Sim
    3. Sim
    4. Sim
3. Sim
    1. Sim
4. Sim
    1. Sim
5. Sim
    1. Sim
6. Sim
    1. Sim
