### ISSUE TITLE
Regras sobre pedidos de dicas

### ISSUE THREAD

**Issue by netojoaobatista** [GrupoDesenvolvimentoWeb/GrupoDesenvolvimentoWeb.github.io#8]
# Regras sobre pedidos de dicas e sugestões

Pedidos de dicas ou sugestões são, em geral, um tema bastante delicado:

* Quando se trata de dicas de ferramentas, hospedagens e similares, esses tipos de pedidos refletem gostos pessoais e raramente motivamos por questões exclusivamente técnicas.
* Quando se trata de dicas sobre um código, layout ou qualquer coisa que em que o autor do pedido esteja trabalhando, esses tipos de pedidos tendem a ser altamente críticos, podendo, eventualmente, ferir emocionalmente o autor da dúvida.
    * entenda as críticas como meio para alcançar a excelência. Nunca leve uma crítica para o lado pessoal;
    * se você recebeu uma crítica que é pessoalmente ofensiva, avise aos administradores. Jamais replique a ofensa. Deixe que os administradores apliquem as regras da comunidade;

Além disso, esses pedidos são altamente recorrentes, poluindo o feed do grupo e dificultando a leitura. Antes de postar qualquer pedido de dica, leia atentamente as regras abaixo:

## Para todos os tipos de pedidos de dicas ou sugestões

1. Antes de postar qualquer pedido de dica, use a pesquisa interna do grupo.
    1. Muito provavelmente alguém já fez exatamente o mesmo pedido que você e uma discussão com várias sugestões já existe;
    2. mantenha sempre a discussão no post do pedido de dica mais antigo;
    3. evite criar novos posts com o mesmo tema, exceto se for estritamente necessário.
2. Se você não tiver uma sugestão fundamentada em argumentos técnicos sobre uma dica, prefira não comentar.
    1. Evite abordar o tema, especialmente sobre ferramentas, com argumentos passionais; eles tendem a causar brigas entre os membros.
3. Pedidos de feedback, dicas de layout e avaliações de projetos **devem ser evitados**. Utilize o grupo [FeedbackDev](https://www.facebook.com/groups/feedbackdev/) para isso.
4. Pedidos de análises de qualidade de código são permitidos, mas esteja ciente de que quando você posta um pedido desses, você está abrindo seu trabalho para críticas.
    1. Os membros do grupo sempre respeitarão uns aos outros, mas o respeito é dedicado ao membro como pessoa, não ao código;
    2. códigos, quando postados, serão criticados. Entenda as críticas como meio para alcançar a excelência. Nunca leve uma crítica para o lado pessoal;
    3. se você recebeu uma crítica que é pessoalmente ofensiva, avise aos administradores. Jamais replique a ofensa. Deixe que os administradores apliquem as regras da comunidade;
    4. se você não souber como fundamentar sua crítica de forma técnica, prefira não comentar.
5. Pedidos de sugestões de boas práticas de desenvolvimento são permitidos.

## Como votar

Poste o número do item seguido de um ponto e sim ou não conforme sua preferência. Se o item tiver subitens, basta indentar o subitem e seguir o padrão anterior. Por exemplo:

```
1. Sim
    1. Sim
    2. Sim
    3. Sim
2. Sim
    1. Sim
3. Sim
4. Sim
    1. Sim
    2. Sim
    3. Sim
    4. Sim
5. Sim
```

**Comment by andersonvs** [comment]
1. Sim
    1. Sim
    2. Sim
    3. Sim
2. Sim
    1. Sim
3. Sim
4. Sim
    1. Sim
    2. Sim
    3. Sim
    4. Sim
5. Sim

**Comment by annielmenezes** [comment]
```
1. Sim
    1. Sim
    2. Sim
    3. Sim
2. Sim
    1. Sim
3. Sim
4. Sim
    1. Sim
    2. Sim
    3. Sim
    4. Sim
5. Sim
```

Uma boa di

**Comment by robertopc** [comment]
1. Sim
    1. Sim
    2. Sim
    3. Sim
2. Sim
    1. Sim
3. Sim
4. Sim
    1. Sim
    2. Sim
    3. Sim
    4. Sim
5. Sim

P.s.: Alguns temas poderiam ter enquete fixa, pra evitar o flood. Exemplo: hospedagens, ide's

**Comment by netojoaobatista** [comment]
@robertopc, vamos fazer uma compilação desses temas num futuro.

Assim que a compilação estiver pronta, criaremos um documento em Markdown com os pontos de vista dos membros do grupo. Esse documento ficará publicamente visível. Se algum membro quiser colaborar com alguma sugestão ao documento, bastará criar um Pull Request. Dessa forma, com um documento facilmente acessível, acho que conseguiremos diminuir o flood no grupo.

**Comment by brunoracosta** [comment]
1. Sim
    1. Sim
    2. Sim
    3. Sim
2. Sim
    1. Sim
3. Sim
4. Sim
    1. Sim
    2. Sim
    3. Sim
    4. Sim
5. Sim

**Comment by edsonlimadev** [comment]
1. Sim
    1. Sim
    2. Sim
    3. Sim
2. Sim
    1. Sim
3. Sim
4. Sim
    1. Sim
    2. Sim
    3. Sim
    4. Sim
5. Sim

**Comment by marcioabraz** [comment]
1. Sim
    1. Sim
    2. Sim
    3. Sim
2. Sim
    1. Sim
3. Sim
4. Sim
    1. Sim
    2. Sim
    3. Sim
    4. Sim
5. Sim

**Comment by samuelcatalano** [comment]
1. Sim
    1. Sim
    2. Sim
    3. Sim
2. Sim
    1. Sim
3. Sim
4. Sim
    1. Sim
    2. Sim
    3. Sim
    4. Sim
5. Sim

**Comment by lucascdsilva** [comment]
1. Sim
    1. Sim
    2. Sim
    3. Sim
2. Sim
    1. Sim
3. Sim
4. Sim
    1. Sim
    2. Sim
    3. Sim
    4. Sim
5. Sim

**Comment by alanmazzilli** [comment]
1. Sim
    1. Sim
    2. Sim
    3. Sim
2. Sim
    1. Sim
3. Sim
4. Sim
    1. Sim
    2. Sim
    3. Sim
    4. Sim
5. Sim

**Comment by augustolima** [comment]
1. Sim
    1. Sim
    2. Sim
    3. Sim
2. Sim
    1. Sim
3. Sim
4. Sim
    1. Sim
    2. Sim
    3. Sim
    4. Sim
5. Sim

**Comment by devmob2you** [comment]
1. Sim
   i. Sim
   ii. Sim
   iii. Sim
2. Sim
   i. Sim
3. Sim
4. Sim
   i. Sim
   ii. Sim
   iii. Sim
   iv. Sim
5. Sim

**Comment by Jeanhsc** [comment]
1. Sim 

    i. Sim 
    ii. Sim 
    iii. Sim 

2. Sim 

    i. Sim 

3. Sim 

4. Sim 

    i. Sim 
    ii. Sim 
    iii. Sim 
    iv. Sim 

5. Sim

**Comment by luizfnunes** [comment]
1. Sim
    i. Sim
    ii. Sim
    iii. Sim
2. Sim
    i. Sim
3. Sim
4. Sim
    i. Sim
    ii. Sim
    iii. Sim
    iv. Sim
5. Sim
